# Credit Risk Evaluator

In [33]:
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [34]:
# Import the data

df = pd.read_csv("Resources/lending_data.csv")
df

loan_size  interest_rate  borrower_income  debt_to_income  \
0        10700.0          7.672            52800        0.431818   
1         8400.0          6.692            43600        0.311927   
2         9000.0          6.963            46100        0.349241   
3        10700.0          7.664            52700        0.430740   
4        10800.0          7.698            53000        0.433962   
...          ...            ...              ...             ...   
77531    19100.0         11.261            86600        0.653580   
77532    17700.0         10.662            80900        0.629172   
77533    17600.0         10.595            80300        0.626401   
77534    16300.0         10.068            75300        0.601594   
77535    15600.0          9.742            72300        0.585062   

       num_of_accounts  derogatory_marks  total_debt  loan_status  
0                    5                 1       22800            0  
1                    3                 0       13600            0  
2                    3                 0       16100            0  
3                    5                 1       22700            0  
4                    5                 1       23000            0  
...                ...               ...         ...          ...  
77531               12                 2       56600            1  
77532               11                 2       50900            1  
77533               11                 2       50300            1  
77534               10                 2       45300            1  
77535                9                 2       42300            1  

[77536 rows x 8 columns]

# Predict Model Performance

You will be creating and comparing two models on this data: a Logistic Regression, and a Random Forests Classifier. Before you create, fit, and score the models, make a prediction as to which model you think will perform better. You do not need to be correct!

Write down your prediction in the designated cells in your Jupyter Notebook, and provide justification for your educated guess.

Prediction: I predict Random Forest Classifier would outperform for its accuracy as it emphasizes feature selection and would play a great role when there are more number of features by handling noise.Random forests takes random samples and forms many decision trees,then averages out the leaf nodes to predict the result.As the target data is categorical I would prefer Logistic Regression.

# Split the Data into Training and Testing Sets

In [35]:
# Define the X (features) and y (target) sets
y = df["loan_status"].values
X = df.drop("loan_status", axis=1)

In [36]:
X

loan_size  interest_rate  borrower_income  debt_to_income  \
0        10700.0          7.672            52800        0.431818   
1         8400.0          6.692            43600        0.311927   
2         9000.0          6.963            46100        0.349241   
3        10700.0          7.664            52700        0.430740   
4        10800.0          7.698            53000        0.433962   
...          ...            ...              ...             ...   
77531    19100.0         11.261            86600        0.653580   
77532    17700.0         10.662            80900        0.629172   
77533    17600.0         10.595            80300        0.626401   
77534    16300.0         10.068            75300        0.601594   
77535    15600.0          9.742            72300        0.585062   

       num_of_accounts  derogatory_marks  total_debt  
0                    5                 1       22800  
1                    3                 0       13600  
2                    3                 0       16100  
3                    5                 1       22700  
4                    5                 1       23000  
...                ...               ...         ...  
77531               12                 2       56600  
77532               11                 2       50900  
77533               11                 2       50300  
77534               10                 2       45300  
77535                9                 2       42300  

[77536 rows x 7 columns]

In [37]:
y

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [38]:
# Split the data into X_train, X_test, y_train, y_test
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)


# Create, Fit and Compare Models

# Logistic Regression

In [39]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression().fit(X_train,y_train)
print(f"Training Data Score: {classifier.score(X_train, y_train)}")
print(f"Testing Data Score: {classifier.score(X_test, y_test)}")

Training Data Score: 0.9919177328380795
Testing Data Score: 0.9924680148576145


In [40]:
# Scale the training and testing data
scaler = StandardScaler().fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [41]:
# Train a Logistic Regression model and print the model score
classifier = LogisticRegression().fit(X_train_scaled, y_train)
classifier

LogisticRegression()

In [42]:
print(f"Scaled Training Data Score: {classifier.score(X_train_scaled, y_train)}")
print(f"Scaled Testing Data Score: {classifier.score(X_test_scaled, y_test)}")

Scaled Training Data Score: 0.9941188609162196
Scaled Testing Data Score: 0.9941704498555509


In [43]:
from sklearn.metrics import confusion_matrix

y_true = y_test
y_pred = classifier.predict(X_test_scaled)
confusion_matrix(y_true, y_pred)

array([[18690,   102],
       [   11,   581]], dtype=int64)

In [44]:
print(f'Actual:\t\t{list(y_test[:25])}')
print(f'Predicted:\t{list(classifier.predict(X_test_scaled[:25]))}')

Actual:		[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Predicted:	[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [45]:
from sklearn.metrics import accuracy_score
score = accuracy_score(y_test,y_pred)
score

0.9941704498555509

# Random Forest Classifier

In [50]:
clf = RandomForestClassifier(random_state=42, n_estimators=1000).fit(X_train, y_train)
print(f'Training Score: {clf.score(X_train, y_train)}')
print(f'Testing Score: {clf.score(X_test, y_test)}')

Training Score: 0.9971970009629936
Testing Score: 0.9921584812216261


In [51]:
# from sklearn.preprocessing import StandardScaler
scaler = StandardScaler().fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [52]:
clf = RandomForestClassifier(random_state=42, n_estimators=1000).fit(X_train_scaled, y_train)
print(f'Scaled Training Data Score: {clf.score(X_train_scaled, y_train)}')
print(f'Scaled Testing Data Score: {clf.score(X_test_scaled, y_test)}')

Scaled Training Data Score: 0.9971970009629936
Scaled Testing Data Score: 0.9918489475856377


In [49]:
y_true = y_test
y_pred = classifier.predict(X_test_scaled)
confusion_matrix(y_true, y_pred)

array([[18690,   102],
       [   11,   581]], dtype=int64)

Both models performed well giving 99% accuracy.The logistic regression edges out the random forest classifier with slight difference.
Logistic regression-99.4% 
Random Forest Classifier-99.2%
With the given dataset the random forest classifier takes longer to run comparitively.